import { DEFAULT_UPDATE_MANIFEST_URL } from "./constants";

declare const __INSTASIGHTS_CLI_VERSION__: string;
declare const __INSTASIGHTS_UPDATE_MANIFEST_URL__: string;

export const EMBEDDED_CLI_VERSION =
  typeof __INSTASIGHTS_CLI_VERSION__ !== "undefined"
    ? __INSTASIGHTS_CLI_VERSION__
    : process.env.INSTASIGHTS_EMBEDDED_VERSION ?? "1.0.0";

export const EMBEDDED_UPDATE_MANIFEST_URL =
  typeof __INSTASIGHTS_UPDATE_MANIFEST_URL__ !== "undefined"
    ? __INSTASIGHTS_UPDATE_MANIFEST_URL__
    : process.env.INSTASIGHTS_EMBEDDED_UPDATE_MANIFEST_URL ??
      DEFAULT_UPDATE_MANIFEST_URL;
